= arch-install

This is an automated setup of my personal archlinux environment. Please use the sources here only to get inspiration and take them into your own setup instead of running the scripts as they are on your system, because they are tailored to me. If you want to automate the setup of your own environment, I highly recommend the book by https://github.com/Phantas0s[Matthieu Cneude] called https://themouseless.dev/[Building your Mouseless Development Environment] for automating vanilla setup and some explanations or just use a https://distrowatch.com/[distro] that matches your requirements. Of course, the https://wiki.archlinux.org/title/Main_page[Arch Wiki] is also a great resource.

== Vanilla Installation

I am not really maintaining the vanilla installation anymore but I keep it as an example.

Prepare an https://archlinux.org/download/[Arch Linux live system] (e.g. on an USB stick) and boot your system from it. If you do not have an US keyboard layout you can load the right keybindings with `loadkeys <country code>` to enter the first commands more easily. I have a german keyboard layout:

    loadkeys de-latin1

If you are connected to the internet via cable, you can skip to 'Download the installation script'. Otherwise you have to connect to the internet manually to be able to download the installation script. Enter `iwctl` to scan and connect to a WiFi network:

    iwctl

List the available devices:

    [iwd]# device list

Choose a device and get the available networks:

    [iwd]# station <device> get-networks

Choose a network and connect to it. Enter the password if necessary:

    [iwd]# station <device> connect "<network>"

After that you can exit iwctl and continue with the installation script.

    [iwd]# exit

Download the installation script:

    curl -LO https://raw.githubusercontent.com/ityreh/arch-install/main/vanilla/install-sys.sh && bash install_sys.sh

== Distro Installation

Instead of installing vanilla Arch you can use a distro of your choice that is based on Arch. The most distro installer are easy to use and you can choose between multiple desktop environments.

Because the distro installation is doing the system setup, we can just install our apps right after it:

    curl -LO https://raw.githubusercontent.com/ityreh/arch-install/main/<distro>/install-apps.sh && bash install-apps.sh

> For more information about my configuration have a look at https://github.com/ityreh/.dotfiles[.dotfiles].
